### PR TITLE
Update core.py

### PR DESCRIPTION
**Pull request by NathanFlurry**
Changed path of settings file

### CODE REVIEW

**Comment by cadyyan** [comment]
OK I see the issue. The problem is that its looking for a configuration file called `mcserver.settings` in the directory where the server is located. It does NOT create this file for you if it doesn't exist. The file is in JSON format so you could just write this to the file to get started and do more of the configuration later.

    {
    }

The available configuration options should be documented in the readme file.

**Comment by cadyyan** [comment]
Fixed by: 44893be528063d25d0b2305c9d24be4605c49f3c

**Comment by NathanFlurry** [comment]
You also have the same issue with `server.properties`.

Along with that, you might want to mention that this product has nothing to do with [this MCServer](http://mc-server.org). I ran across this tool, assuming this was a tool for MCServer (since it says "MCServer" everywhere), but it's not. (I feel really dumb now. 😐)

Thanks,
Nathan

**Comment by cadyyan** [comment]
Oh wow I didn't even know that existed. Thanks for the feedback.

**Pull request closed without merging**
